### ISSUE TITLE
zclassic.org 

### ISSUE THREAD

**Issue by sneg55** [z-classic/z-classic.github.io#39]
It looks like current zclassic.org  is slightly different from the repo copy: https://github.com/z-classic/z-classic.github.io/blob/master/index.html

**Comment by sneg55** [comment]
@heyrhett just want to bring this to your attention

**Comment by nimbosa** [comment]
i think it was likely pulling form develop instead of master, for BTCP pre-fork announcement

**Comment by sneg55** [comment]
@nimbosa  is there any chances to fix it?

**Comment by nimbosa** [comment]
it's back to using master and we have successfully updated it, will soon remove stale references to BTCP, 

Thanks for keeping an eye on it..
