### ISSUE TITLE
Image scaling makes logo look fuzzy

### ISSUE THREAD

**Issue by joshuayabut** [z-classic/z-classic.github.io#9]
The top left logo probably might need to be resized natively or have the font blur adjusted. It comes out really washed out on my screen. http://zclassic.org/img/logo-light.png

![](https://i.imgur.com/L7AqEvt.png "Screenshot")

**Comment by jojozcl** [comment]
Well seen : https://github.com/z-classic/z-classic.github.io/commit/8e5d7a3b5deefeca61dbddc763b31f856e046ad5
